format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Menu
    attributes: {id: SYS_WIFI_APPDEBUG_FLOW_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: SYS_WIFI_APPDEBUG_LEVEL_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_WIFI_APPDEBUG_PRESTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: SYS_WIFI_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: AP}
  - type: Integer
    attributes: {id: SYS_WIFI_RTOS_DELAY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '4'}
  - type: Boolean
    attributes: {id: SYS_WIFI_STA_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '251', y: '21', id: sysWifiPic32mzw1}
